# Generated by Django 5.1.3 on 2024-11-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='consequence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('no_individuals', models.IntegerField()),
                ('submission_date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='submission',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
        ),
    ]
