# Generated by Django 5.1.3 on 2024-11-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variant_consequence_submission_variant_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
        ),
    ]
