# Generated by Django 5.1.3 on 2024-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_variant_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
