# Generated by Django 5.1.3 on 2024-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='gene_name',
            field=models.CharField(max_length=255),
        ),
    ]
