# Generated by Django 5.1.3 on 2024-12-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_variant_gene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.variant'),
        ),
    ]
