# Generated by Django 5.1.3 on 2024-12-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_frequency_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='last_updated',
            field=models.IntegerField(null=True),
        ),
    ]
