# Generated by Django 5.1.3 on 2025-01-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_frequency_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNV',
            fields=[
                ('variation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('chromosome', models.IntegerField()),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('site_count', models.IntegerField()),
                ('consequence', models.CharField(max_length=255, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.submission')),
            ],
            options={
                'db_table': 'mt50variants',
            },
        ),
    ]
