# Generated by Django 5.1.3 on 2025-01-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cnv'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cnv',
            table='mt50_variants',
        ),
    ]
