# Generated by Django 5.1.3 on 2025-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cnv_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnv',
            name='chromosome',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='variant',
            name='chromosome',
            field=models.CharField(max_length=8),
        ),
    ]
