# Generated by Django 5.1.3 on 2025-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cnv_chromosome_alter_variant_chromosome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnv',
            name='last_updated',
            field=models.JSONField(null=True),
        ),
    ]
