# Generated by Django 5.1.3 on 2025-04-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cnv_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarCounts',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cnv_count', models.IntegerField(default=0)),
                ('ssv_count', models.IntegerField(default=0)),
                ('exo_count', models.IntegerField(default=0)),
                ('intro_count', models.IntegerField(default=0)),
                ('inter_count', models.IntegerField(default=0)),
                ('reg_count', models.IntegerField(default=0)),
                ('spli_count', models.IntegerField(default=0)),
                ('intra_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'var_counts',
            },
        ),
    ]
